branches:
  except:
  - l10n_master
language: perl
perl:
  - "system"
env: COVERAGE=1
cache:
  directories:
  - $HOME/.npm
  - $HOME/.cache
  - $HOME/perl5
addons:
  apt:
    packages:
    - libapache2-request-perl
    - libimage-magick-perl
    - libbarcode-zbar-perl
    - tesseract-ocr
    - graphviz
sudo: false
before_install:
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
install:
  - cpanm --quiet --installdeps --notest --skip-satisfied .
  - npm install
  - bower install
  - ln -s $TRAVIS_BUILD_DIR/lib/ProductOpener/Config_off.pm $TRAVIS_BUILD_DIR/lib/ProductOpener/Config.pm
  - cp $TRAVIS_BUILD_DIR/lib/ProductOpener/Config2_sample.pm $TRAVIS_BUILD_DIR/lib/ProductOpener/Config2.pm
  - ln -s $TRAVIS_BUILD_DIR/lib/ProductOpener/SiteLang_off.pm $TRAVIS_BUILD_DIR/lib/ProductOpener/SiteLang.pm
  - sed -i -e 's|\$server_domain = "openfoodfacts.org";|\$server_domain = "off.travis-ci.org";|g' $TRAVIS_BUILD_DIR/lib/ProductOpener/Config2.pm
  - sed -i -e 's|\/home\/off|'$TRAVIS_BUILD_DIR'|g' $TRAVIS_BUILD_DIR/lib/ProductOpener/Config2.pm
script:
  - prove -l
  - perl -c -CS -I$TRAVIS_BUILD_DIR/lib lib/startup_apache2.pl
  - jshint --show-non-errors html/js/product-multilingual.js html/js/search.js
notifications:
  slack: openfoodfacts:Pre9ZXKFH1CYtix8DeJAaFi2
